version: '3'
services:
  zmifanva:
    image: 'olpa/zmifanva'
    ports:
      - '6543:6543'
    environment:
      MOSES_SERVER_JB2EN: 'http://jb-en:8080'
      MOSES_SERVER_EN2JB: 'http://en-jb:8080'
  jb-en:
    image: 'olpa/moses-zf-jb-en'
    command: 'opt/moses/bin/moses --server --server-port 8080 -f /zmifanva/moses_model/jb-en/moses.ini'
  en-jb:
    image: 'olpa/moses-zf-en-jb'
    command: 'opt/moses/bin/moses --server --server-port 8080 -f /zmifanva/moses_model/en-jb/moses.ini'
